# Change this variables to reflect your environment

# Your Gx Instance URL
gx_base_url = 'https://qcbox-270123.kneatgxdev.com/888888-QCBox-270123/'

# Your Token Service URL
token_service_url = 'https://qcbox-270123.kneatgxdev.com/888888-QCBox-270123/token'

# Replace with your client ID
client_id = '901ad0d0-a0d8-11ed-8194-47b99521b7e3'

# The redirect URI you registered on the External Application page, this url is generated by this application
callback_uri = 'http://127.0.0.1:5198/callback_oauth'
